### ISSUE TITLE
Error while creating a new app with spaces in name

### ISSUE THREAD

**Issue by thinkh** [Caleydo/caleydo_web_container#138]
# Instruction to reproduce

I wanted to create a new app and the wizzard asked me a couple of questions.

Here are the things I entered:
- `plugin name:` my_first_app
- `name:` My First App
- version: (0.0.1)
- keywords: sample, demo
- author: Holger
- license: (SEE LICENSE IN LICENSE) MIT

At the end the creation process fails.

Here is the full console output:

```
vagrant@caleydo-web:/vagrant$ ./manage.sh init
Enter the plugin name : my_first_app
Cloning into 'my_first_app'...
remote: Counting objects: 12, done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
Unpacking objects: 100% (12/12), done.
Checking connectivity... done.
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sane defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (sample_web) My First App
version: (0.0.1)
keywords: sample, demo
author: Holger
license: (SEE LICENSE IN LICENSE) MIT
npm ERR! Error: Invalid name: "My First App"
npm ERR!     at ensureValidName (/usr/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:315:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:204:5)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
npm ERR!     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:342:33)
npm ERR!     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at gypfile_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:158:43)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:153:33
npm ERR!     at f (/usr/lib/node_modules/npm/node_modules/once/once.js:16:25)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-77-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "init"
npm ERR! cwd /vagrant/plugins/my_first_app
npm ERR! node -v v0.10.41
npm ERR! npm -v 1.4.29
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /vagrant/plugins/my_first_app/npm-debug.log
npm ERR! not ok code 0
ready
```
# Expected

Handle any name or give an user friendly error message and let the user repeat the input.

**Comment by sgratzl** [comment]
my npm prohibits that I'm entering an invalid name

**Comment by sgratzl** [comment]
->phovea
